version: '3.9'

services:
  ticat-dev-postgresql:
    image: bitnami/postgresql:16.1.0
    container_name: ticat-dev-postgresql
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./dbdata:/bitnami/postgresql
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgressupersecret

  ticat-dev-keycloak:
    container_name: ticat-dev-keycloak
    image: bitnami/keycloak:22.0.5
    restart: unless-stopped
    depends_on:
      - postgresql
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=adminsupersecret
      - KEYCLOAK_DATABASE_HOST=postgresql
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_USER=keycloak
      - KEYCLOAK_DATABASE_PASSWORD=keycloaksupersecret
      - KEYCLOAK_HTTP_PORT=8080
      - PROXY_ADDRESS_FORWARDING=true
    ports:
      - "8080:8080"
